"""
AWS D1.1/D1.1M:2020 — Annex J Sample Forms
LaTeX template generators for professional PDF output via latex.ytotech.com API.

Forms included:
  J-1  Procedure Qualification Record (PQR)
  J-2  Welding Procedure Specification (WPS)
  J-3  WPS Qualification Test Record — Electroslag / Electrogas Welding
  J-4  Welder / Welding Operator / Tack Welder Qualification (Single-Process)
  J-5  Welder / Welding Operator / Tack Welder Qualification (Multi-Process)
  J-6  Report of Radiographic Examination of Welds
  J-7  Report of Magnetic Particle Examination of Welds
"""

import requests, io


# ═══════════════════════════════════════════════════════════════════════
#  SHARED HELPERS
# ═══════════════════════════════════════════════════════════════════════

def _esc(text):
    """Escape special LaTeX characters in user‑supplied text."""
    s = str(text) if text else "---"
    for ch in ['\\', '&', '%', '$', '#', '_', '{', '}', '~', '^']:
        s = s.replace(ch, '\\' + ch)
    return s


_PREAMBLE = r"""
\documentclass[a4paper,9pt]{article}
\usepackage[margin=10mm]{geometry}
\usepackage{booktabs,tabularx,colortbl,xcolor,array,multirow}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{fancyhdr}
\usepackage{lastpage}

% ── Colours ──
\definecolor{darkblue}{HTML}{1A3A5C}
\definecolor{lightblue}{HTML}{D6E4F0}
\definecolor{verylightblue}{HTML}{EBF0F7}
\definecolor{lightgray}{HTML}{F5F5F5}
\definecolor{midgray}{HTML}{CCCCCC}

% ── Column types ──
\newcolumntype{H}{>{\columncolor{darkblue}\color{white}\bfseries\scriptsize}l}
\newcolumntype{D}{>{\columncolor{lightblue}\bfseries\scriptsize}l}
\newcolumntype{V}{>{\scriptsize}X}
\newcolumntype{S}{>{\scriptsize}l}

% ── Page style ──
\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0pt}
"""

_DOC_BEGIN = r"""
\setlength{\parindent}{0pt}
\setlength{\tabcolsep}{3pt}
\renewcommand{\arraystretch}{1.30}
\begin{document}
"""


def _footer(form_id, form_title):
    return (
        r"\fancyfoot[C]{\scriptsize\color{gray} "
        + _esc(f"Form {form_id}")
        + r" \textbar\ AWS D1.1/D1.1M:2020 --- Annex J \textbar\ "
        + _esc(form_title)
        + r" \textbar\ Generated by Welding Engineering Toolbox \textbar\ "
        + r"Page \thepage\ of \pageref{LastPage}}"
    )


def _title_block(form_id, form_title, standard="AWS D1.1/D1.1M:2020"):
    return (
        r"\begin{center}"
        + "\n"
        + r"  {\large\bfseries\color{darkblue} " + _esc(form_title).upper() + r"}\\"
        + "\n"
        + r"  {\scriptsize\color{darkblue} " + _esc(standard) + r" --- Annex J, " + _esc(f"Form {form_id}") + r"}"
        + "\n"
        + r"\end{center}" + "\n"
        + r"\vspace{2pt}" + "\n"
    )


def _section(title):
    """Dark blue full‑width section header row (standalone tabularx)."""
    return (
        r"\noindent"
        + r"\begin{tabularx}{\textwidth}{|>{\columncolor{darkblue}\color{white}\bfseries\scriptsize}X|}"
        + "\n" + r"\hline " + _esc(title) + r" \\ \hline"
        + "\n" + r"\end{tabularx}" + "\n"
        + r"\nointerlineskip" + "\n"
    )


def _sig_block():
    """Standard three‑column signature block."""
    return r"""
\vspace{6pt}
\noindent
\begin{tabularx}{\textwidth}{|X|X|X|}
\hline
\rowcolor{darkblue} \textcolor{white}{\textbf{\scriptsize Written By}} &
\textcolor{white}{\textbf{\scriptsize Reviewed By}} &
\textcolor{white}{\textbf{\scriptsize Approved By}} \\
\hline
\vspace{14pt} & \vspace{14pt} & \vspace{14pt} \\
{\scriptsize Name: \hrulefill} & {\scriptsize Name: \hrulefill} & {\scriptsize Name: \hrulefill} \\
{\scriptsize Date: \hrulefill} & {\scriptsize Date: \hrulefill} & {\scriptsize Date: \hrulefill} \\
\hline
\end{tabularx}
"""


def compile_latex(latex_src):
    """Send LaTeX source to latex.ytotech.com and return (success, data_or_error)."""
    try:
        resp = requests.post(
            "https://latex.ytotech.com/builds/sync",
            json={
                "compiler": "pdflatex",
                "resources": [{"main": True, "content": latex_src}]
            },
            timeout=90,
        )
        if resp.status_code in (200, 201) and resp.content[:5] == b"%PDF-":
            return True, resp.content
        else:
            return False, resp.text[:2000] if resp.text else "Empty response"
    except requests.exceptions.Timeout:
        return False, "Compilation timed out — the service may be busy."
    except Exception as e:
        return False, str(e)


# ═══════════════════════════════════════════════════════════════════════
#  FORM J-1 — PROCEDURE QUALIFICATION RECORD (PQR)
# ═══════════════════════════════════════════════════════════════════════

def latex_j1(d):
    """Generate LaTeX for Form J‑1 PQR.  `d` is a dict of field values."""
    g = lambda k: _esc(d.get(k, ""))
    src = _PREAMBLE + _footer("J-1", "Procedure Qualification Record (PQR)") + _DOC_BEGIN
    src += _title_block("J-1", "Procedure Qualification Record (PQR)")

    # ── Header ──
    src += _section("DOCUMENT INFORMATION")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Company & {g('company')} & PQR No. & {g('pqr_no')} & Date & {g('date')} \\\\
\\hline
WPS No. & {g('wps_no')} & Welding Process(es) & {g('process')} & Type(s) & {g('process_type')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Joint Design ──
    src += _section("JOINT DESIGN USED")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Joint Type & {g('joint_type')} & Groove Angle & {g('groove_angle')} \\\\
\\hline
Root Opening & {g('root_opening')} & Root Face & {g('root_face')} \\\\
\\hline
Backing & {g('backing')} & Backing Material & {g('backing_material')} \\\\
\\hline
Sketch/Drawing No. & \\multicolumn{{3}}{{l|}}{{{g('sketch')}}} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Base Metals ──
    src += _section("BASE METALS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Specification & {g('bm_spec')} & Type or Grade & {g('bm_grade')} \\\\
\\hline
To Specification & {g('bm_spec2')} & Type or Grade & {g('bm_grade2')} \\\\
\\hline
Thickness & {g('bm_thickness')} & Diameter & {g('bm_diameter')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Filler Metals ──
    src += _section("FILLER METALS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""AWS Specification & {g('fm_spec')} & AWS Classification & {g('fm_class')} \\\\
\\hline
F-Number & {g('fm_fno')} & A-Number & {g('fm_ano')} \\\\
\\hline
Filler Metal Diameter & {g('fm_dia')} & Supplemental Filler & {g('fm_supplement')} \\\\
\\hline
Flux & {g('fm_flux')} & Flux Trade Name & {g('fm_flux_trade')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Position / Preheat / PWHT ──
    src += _section("POSITION / PREHEAT / PWHT")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Position & {g('position')} & Progression & {g('progression')} & & \\\\
\\hline
Preheat Temp. & {g('preheat')} & Interpass Temp. & {g('interpass')} & & \\\\
\\hline
PWHT Temp. & {g('pwht_temp')} & PWHT Time & {g('pwht_time')} & PWHT Other & {g('pwht_other')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Shielding / Electrical ──
    src += _section("SHIELDING / ELECTRICAL CHARACTERISTICS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Shielding Gas & {g('shield_gas')} & Flow Rate & {g('gas_flow')} & Backing Gas & {g('back_gas')} \\\\
\\hline
Current Type & {g('current')} & Polarity & {g('polarity')} & & \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Welding Parameters Table ──
    src += _section("WELDING PARAMETERS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|S|S|V|V|V|V|V|V|}
\hline
\rowcolor{darkblue}
\textcolor{white}{\textbf{\scriptsize Pass}} &
\textcolor{white}{\textbf{\scriptsize Process}} &
\textcolor{white}{\textbf{\scriptsize Filler Dia.}} &
\textcolor{white}{\textbf{\scriptsize Amps}} &
\textcolor{white}{\textbf{\scriptsize Volts}} &
\textcolor{white}{\textbf{\scriptsize Travel Speed}} &
\textcolor{white}{\textbf{\scriptsize Wire Feed}} &
\textcolor{white}{\textbf{\scriptsize Heat Input}} \\
\hline
"""
    passes = d.get("passes", [])
    if passes:
        for i, p in enumerate(passes):
            bg = r"\rowcolor{lightgray}" if i % 2 == 0 else ""
            src += f"{bg} {_esc(p.get('pass',''))} & {_esc(p.get('process',''))} & {_esc(p.get('filler_dia',''))} & {_esc(p.get('amps',''))} & {_esc(p.get('volts',''))} & {_esc(p.get('travel',''))} & {_esc(p.get('wire_feed',''))} & {_esc(p.get('heat_input',''))} \\\\\n\\hline\n"
    else:
        for i in range(4):
            bg = r"\rowcolor{lightgray}" if i % 2 == 0 else ""
            src += f"{bg} & & & & & & & \\\\\n\\hline\n"

    src += r"""
\end{tabularx}
\vspace{3pt}
"""

    # ── Test Results ──
    src += _section("TEST RESULTS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Visual Inspection & {g('visual')} & Result & {g('visual_result')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{2pt}}
"""

    # Guided Bend Tests
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|S|V|V|V|}
\hline
\rowcolor{darkblue}
\textcolor{white}{\textbf{\scriptsize Guided Bend Test}} &
\textcolor{white}{\textbf{\scriptsize Type}} &
\textcolor{white}{\textbf{\scriptsize Result}} &
\textcolor{white}{\textbf{\scriptsize Remarks}} \\
\hline
"""
    bends = d.get("bend_tests", [])
    if bends:
        for i, b in enumerate(bends):
            bg = r"\rowcolor{lightgray}" if i % 2 == 0 else ""
            src += f"{bg} {_esc(b.get('specimen',''))} & {_esc(b.get('type',''))} & {_esc(b.get('result',''))} & {_esc(b.get('remarks',''))} \\\\\n\\hline\n"
    else:
        for i in range(4):
            bg = r"\rowcolor{lightgray}" if i % 2 == 0 else ""
            src += f"{bg} Specimen {i+1} & & & \\\\\n\\hline\n"

    src += r"""
\end{tabularx}
\vspace{2pt}
"""

    # Tension Tests
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|S|V|V|V|V|V|}
\hline
\rowcolor{darkblue}
\textcolor{white}{\textbf{\scriptsize Tension Test}} &
\textcolor{white}{\textbf{\scriptsize Width}} &
\textcolor{white}{\textbf{\scriptsize Thickness}} &
\textcolor{white}{\textbf{\scriptsize Area}} &
\textcolor{white}{\textbf{\scriptsize Ult. Load}} &
\textcolor{white}{\textbf{\scriptsize Ult. Stress (psi)}} \\
\hline
"""
    tensions = d.get("tension_tests", [])
    if tensions:
        for i, t in enumerate(tensions):
            bg = r"\rowcolor{lightgray}" if i % 2 == 0 else ""
            src += f"{bg} {_esc(t.get('specimen',''))} & {_esc(t.get('width',''))} & {_esc(t.get('thickness',''))} & {_esc(t.get('area',''))} & {_esc(t.get('load',''))} & {_esc(t.get('stress',''))} \\\\\n\\hline\n"
    else:
        for i in range(2):
            bg = r"\rowcolor{lightgray}" if i % 2 == 0 else ""
            src += f"{bg} Specimen {i+1} & & & & & \\\\\n\\hline\n"

    src += r"""
\end{tabularx}
\vspace{2pt}
"""

    # RT/UT + Other
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""RT/UT Results & {g('rt_ut')} & Fillet Weld Test & {g('fillet_test')} \\\\
\\hline
Macro Exam & {g('macro')} & Other Tests & {g('other_tests')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{2pt}}
"""

    # ── Certification ──
    src += _section("CERTIFICATION")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Tested By & {g('tested_by')} & Test No. & {g('test_no')} \\\\
\\hline
Laboratory & {g('laboratory')} & Date & {g('test_date')} \\\\
\\hline
\\end{{tabularx}}
"""

    src += _sig_block()
    src += r"\end{document}"
    return src


# ═══════════════════════════════════════════════════════════════════════
#  FORM J-2 — WELDING PROCEDURE SPECIFICATION (WPS)
# ═══════════════════════════════════════════════════════════════════════

def latex_j2(d):
    """Generate LaTeX for Form J‑2 WPS.  `d` is a dict of field values."""
    g = lambda k: _esc(d.get(k, ""))
    src = _PREAMBLE + _footer("J-2", "Welding Procedure Specification (WPS)") + _DOC_BEGIN
    src += _title_block("J-2", "Welding Procedure Specification (WPS)")

    # ── Header ──
    src += _section("DOCUMENT HEADER")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|D|V|}
\hline
""" + f"""Company & {g('company')} & WPS No. & {g('wps_no')} & Rev. & {g('rev')} & Date & {g('date')} \\\\
\\hline
Auth.\\ By & {g('auth_by')} & Auth.\\ Date & {g('auth_date')} & PQR(s) & {g('pqr')} & CVN & {g('cvn')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Base Metals ──
    src += _section("BASE METALS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Specification & {g('bm_spec')} & Type / Grade & {g('bm_grade')} & AWS Group No. & {g('bm_group')} \\\\
\\hline
Welded To & {g('bm_welded_to')} & Backing & {g('bm_backing')} & Diameter & {g('bm_diameter')} \\\\
\\hline
\\end{{tabularx}}
\\nointerlineskip
\\noindent
\\begin{{tabularx}}{{\\textwidth}}{{|D|V|V|}}
\\hline
\\rowcolor{{darkblue}} \\textcolor{{white}}{{\\textbf{{\\scriptsize Base Metal Thickness}}}} & \\textcolor{{white}}{{\\textbf{{\\scriptsize As-Welded}}}} & \\textcolor{{white}}{{\\textbf{{\\scriptsize With PWHT}}}} \\\\
\\hline
CJP Groove Welds & {g('thick_cjp_aw')} & {g('thick_cjp_pwht')} \\\\
\\hline
\\rowcolor{{lightgray}} CJP Groove w/CVN & {g('thick_cjp_cvn_aw')} & {g('thick_cjp_cvn_pwht')} \\\\
\\hline
PJP Groove Welds & {g('thick_pjp_aw')} & {g('thick_pjp_pwht')} \\\\
\\hline
\\rowcolor{{lightgray}} Fillet Welds & {g('thick_fillet_aw')} & {g('thick_fillet_pwht')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Joint Details ──
    src += _section("JOINT DETAILS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Groove Type & {g('groove_type')} & Root Opening & {g('root_opening')} \\\\
\\hline
\\rowcolor{{lightgray}} Groove Angle & {g('groove_angle')} & Root Face & {g('root_face')} \\\\
\\hline
Backgouging & {g('backgouging')} & Method & {g('backgouging_method')} \\\\
\\hline
\\rowcolor{{lightgray}} Joint Sketch Notes & \\multicolumn{{3}}{{l|}}{{{g('joint_sketch')}}} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── PWHT ──
    src += _section("POSTWELD HEAT TREATMENT")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Temperature & {g('pwht_temp')} & Time at Temp. & {g('pwht_time')} & Other & {g('pwht_other')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Procedure ──
    src += _section("PROCEDURE")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Weld Layer(s) & {g('weld_layers')} & Weld Pass(es) & {g('weld_passes')} \\\\
\\hline
\\rowcolor{{lightgray}} Process & {g('process')} & Type & {g('process_type')} \\\\
\\hline
Position & {g('position')} & Filler Metal (AWS) & {g('filler_spec')} \\\\
\\hline
\\rowcolor{{lightgray}} AWS Classification & {g('aws_class')} & Electrode Dia. & {g('electrode_dia')} \\\\
\\hline
Electrode/Flux Class. & {g('electrode_flux')} & Manufacturer & {g('manufacturer')} \\\\
\\hline
\\rowcolor{{lightgray}} Supplemental Filler & {g('supplemental')} & Preheat Temp. & {g('preheat')} \\\\
\\hline
Interpass Temp. & {g('interpass')} & Shielding Gas & {g('shielding_gas')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Electrical ──
    src += _section("ELECTRICAL CHARACTERISTICS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Current / Polarity & {g('current_polarity')} & Amps & {g('amps')} & Volts & {g('volts')} \\\\
\\hline
\\rowcolor{{lightgray}} Wire Feed Speed & {g('wire_feed')} & Travel Speed & {g('travel_speed')} & Max Heat Input & {g('max_heat_input')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Technique ──
    src += _section("TECHNIQUE")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Stringer / Weave & {g('stringer_weave')} & Multi/Single Pass & {g('multi_single')} & No.\\ of Electrodes & {g('num_electrodes')} \\\\
\\hline
\\rowcolor{{lightgray}} Long.\\ Spacing & {g('long_spacing')} & Lateral Spacing & {g('lateral_spacing')} & Angle Parallel & {g('angle_parallel')} \\\\
\\hline
Angle of Electrode & {g('angle_electrode')} & Normal to Travel & {g('normal_direction')} & Oscillation & {g('oscillation')} \\\\
\\hline
\\rowcolor{{lightgray}} Traverse Length & {g('traverse_length')} & Traverse Speed & {g('traverse_speed')} & Dwell Time & {g('dwell_time')} \\\\
\\hline
Peening & {g('peening')} & Interpass Cleaning & {g('interpass_cleaning')} & Other & {g('other_tech')} \\\\
\\hline
\\end{{tabularx}}
"""

    src += _sig_block()
    src += r"\end{document}"
    return src


# ═══════════════════════════════════════════════════════════════════════
#  FORM J-3 — WPS TEST RECORD FOR ELECTROSLAG / ELECTROGAS WELDING
# ═══════════════════════════════════════════════════════════════════════

def latex_j3(d):
    g = lambda k: _esc(d.get(k, ""))
    src = _PREAMBLE + _footer("J-3", "WPS Qualification Test Record --- ESW/EGW") + _DOC_BEGIN
    src += _title_block("J-3", "WPS Qualification Test Record — Electroslag / Electrogas Welding")

    src += _section("DOCUMENT INFORMATION")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Company & {g('company')} & WPS No. & {g('wps_no')} & Date & {g('date')} \\\\
\\hline
Process & {g('process')} & Type & {g('process_type')} & PQR No. & {g('pqr_no')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("BASE METALS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Specification & {g('bm_spec')} & Type or Grade & {g('bm_grade')} \\\\
\\hline
To Specification & {g('bm_spec2')} & Type or Grade & {g('bm_grade2')} \\\\
\\hline
Thickness (Groove) & {g('bm_thick_groove')} & Thickness (Fillet) & {g('bm_thick_fillet')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("FILLER METALS / CONSUMABLES")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""AWS Specification & {g('fm_spec')} & AWS Classification & {g('fm_class')} \\\\
\\hline
Electrode Diameter & {g('fm_dia')} & Flux (if applicable) & {g('fm_flux')} \\\\
\\hline
Consumable Guide & {g('consumable_guide')} & Manufacturer & {g('manufacturer')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("JOINT DESIGN")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Joint Type & {g('joint_type')} & Groove Angle & {g('groove_angle')} \\\\
\\hline
Root Opening & {g('root_opening')} & Root Face & {g('root_face')} \\\\
\\hline
Retaining Shoe Type & {g('shoe_type')} & Material & {g('shoe_material')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("WELDING PARAMETERS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Current Type & {g('current')} & Polarity & {g('polarity')} & & \\\\
\\hline
Amps & {g('amps')} & Volts & {g('volts')} & Travel Speed & {g('travel_speed')} \\\\
\\hline
Oscillation & {g('oscillation')} & Dwell Time & {g('dwell_time')} & Electrode Spacing & {g('electrode_spacing')} \\\\
\\hline
No.\\ of Electrodes & {g('num_electrodes')} & No.\\ of Passes & {g('num_passes')} & Preheat & {g('preheat')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("SHIELDING")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Shielding Gas & {g('shield_gas')} & Flow Rate & {g('gas_flow')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("TEST RESULTS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Visual Inspection & {g('visual')} & RT/UT & {g('rt_ut')} \\\\
\\hline
All-Weld-Metal Tension & {g('tension')} & CVN Impact & {g('cvn_impact')} \\\\
\\hline
Macro Exam & {g('macro')} & Other & {g('other_tests')} \\\\
\\hline
Tested By & {g('tested_by')} & Date & {g('test_date')} \\\\
\\hline
\\end{{tabularx}}
"""

    src += _sig_block()
    src += r"\end{document}"
    return src


# ═══════════════════════════════════════════════════════════════════════
#  FORM J-4 — WELDER / WELDING OPERATOR QUALIFICATION (SINGLE-PROCESS)
# ═══════════════════════════════════════════════════════════════════════

def latex_j4(d):
    g = lambda k: _esc(d.get(k, ""))
    src = _PREAMBLE + _footer("J-4", "Welder/Operator Qualification Test Record (Single-Process)") + _DOC_BEGIN
    src += _title_block("J-4", "Welder, Welding Operator, or Tack Welder Qualification Test Record (Single-Process)")

    src += _section("WELDER / OPERATOR INFORMATION")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Name & {g('name')} & ID / Stamp & {g('id_stamp')} & Date & {g('date')} \\\\
\\hline
Company & {g('company')} & WPS No. & {g('wps_no')} & & \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("WELDING VARIABLES")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Process & {g('process')} & Type & {g('process_type')} \\\\
\\hline
\\rowcolor{{lightgray}} Electrode (AWS Spec.) & {g('electrode_spec')} & Classification & {g('electrode_class')} \\\\
\\hline
F-Number & {g('f_number')} & Electrode Diameter & {g('electrode_dia')} \\\\
\\hline
\\rowcolor{{lightgray}} Position & {g('position')} & Progression & {g('progression')} \\\\
\\hline
Backing & {g('backing')} & Backing Type & {g('backing_type')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("TEST BASE METAL")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Specification & {g('bm_spec')} & Grade & {g('bm_grade')} & AWS Group & {g('bm_group')} \\\\
\\hline
Thickness & {g('bm_thickness')} & Diameter & {g('bm_diameter')} & & \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("SHIELDING / THERMAL")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Shielding Gas & {g('shield_gas')} & Flow Rate & {g('gas_flow')} & & \\\\
\\hline
Preheat Temp. & {g('preheat')} & Interpass Temp. & {g('interpass')} & PWHT & {g('pwht')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("ELECTRICAL CHARACTERISTICS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Current & {g('current')} & Polarity & {g('polarity')} & Transfer Mode & {g('transfer_mode')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Test Results ──
    src += _section("TEST RESULTS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Visual Inspection & {g('visual')} & Acceptance Criteria & {g('visual_criteria')} \\\\
\\hline
\\end{{tabularx}}
\\nointerlineskip
"""
    # Guided Bend
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|S|V|V|V|}
\hline
\rowcolor{darkblue}
\textcolor{white}{\textbf{\scriptsize Guided Bend Test}} &
\textcolor{white}{\textbf{\scriptsize Type \& Figure}} &
\textcolor{white}{\textbf{\scriptsize Result}} &
\textcolor{white}{\textbf{\scriptsize Remarks}} \\
\hline
"""
    bends = d.get("bend_tests", [])
    for i in range(max(4, len(bends))):
        bg = r"\rowcolor{lightgray}" if i % 2 == 0 else ""
        if i < len(bends):
            b = bends[i]
            src += f"{bg} {_esc(b.get('specimen',''))} & {_esc(b.get('type',''))} & {_esc(b.get('result',''))} & {_esc(b.get('remarks',''))} \\\\\n\\hline\n"
        else:
            src += f"{bg} Specimen {i+1} & & & \\\\\n\\hline\n"

    src += r"""
\end{tabularx}
\nointerlineskip
"""

    # RT/Fillet/Macro
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""RT/UT Results & {g('rt_ut')} & Fillet Weld Break & {g('fillet_break')} \\\\
\\hline
Macro Exam & {g('macro')} & Other Tests & {g('other_tests')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # ── Ranges Qualified ──
    src += _section("RANGES QUALIFIED")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Process & {g('qual_process')} & Electrode Group (F-No.) & {g('qual_f_number')} \\\\
\\hline
\\rowcolor{{lightgray}} Positions & {g('qual_positions')} & Weld Type (Groove/Fillet) & {g('qual_weld_type')} \\\\
\\hline
Thickness Range & {g('qual_thickness')} & Diameter Range & {g('qual_diameter')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("CERTIFICATION")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Tested By & {g('tested_by')} & Test No. & {g('test_no')} \\\\
\\hline
Employer & {g('employer')} & Date & {g('test_date')} \\\\
\\hline
\\end{{tabularx}}
"""

    src += _sig_block()
    src += r"\end{document}"
    return src


# ═══════════════════════════════════════════════════════════════════════
#  FORM J-5 — WELDER / WELDING OPERATOR QUALIFICATION (MULTI-PROCESS)
# ═══════════════════════════════════════════════════════════════════════

def latex_j5(d):
    g = lambda k: _esc(d.get(k, ""))
    src = _PREAMBLE + _footer("J-5", "Welder/Operator Qualification Test Record (Multi-Process)") + _DOC_BEGIN
    src += _title_block("J-5", "Welder, Welding Operator, or Tack Welder Qualification Test Record (Multi-Process)")

    src += _section("WELDER / OPERATOR INFORMATION")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Name & {g('name')} & ID / Stamp & {g('id_stamp')} & Date & {g('date')} \\\\
\\hline
Company & {g('company')} & WPS No. & {g('wps_no')} & & \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # Process 1
    src += _section("PROCESS 1 — WELDING VARIABLES")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Process & {g('p1_process')} & Type & {g('p1_type')} & F-Number & {g('p1_f_number')} \\\\
\\hline
Electrode Spec. & {g('p1_electrode_spec')} & Classification & {g('p1_electrode_class')} & Diameter & {g('p1_electrode_dia')} \\\\
\\hline
Position & {g('p1_position')} & Progression & {g('p1_progression')} & Backing & {g('p1_backing')} \\\\
\\hline
Shielding Gas & {g('p1_shield_gas')} & Current / Polarity & {g('p1_current')} & & \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    # Process 2
    src += _section("PROCESS 2 — WELDING VARIABLES")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Process & {g('p2_process')} & Type & {g('p2_type')} & F-Number & {g('p2_f_number')} \\\\
\\hline
Electrode Spec. & {g('p2_electrode_spec')} & Classification & {g('p2_electrode_class')} & Diameter & {g('p2_electrode_dia')} \\\\
\\hline
Position & {g('p2_position')} & Progression & {g('p2_progression')} & Backing & {g('p2_backing')} \\\\
\\hline
Shielding Gas & {g('p2_shield_gas')} & Current / Polarity & {g('p2_current')} & & \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("TEST BASE METAL")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Specification & {g('bm_spec')} & Grade & {g('bm_grade')} & AWS Group & {g('bm_group')} \\\\
\\hline
Thickness & {g('bm_thickness')} & Diameter & {g('bm_diameter')} & & \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("TEST RESULTS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Visual Inspection & {g('visual')} & Acceptance Criteria & {g('visual_criteria')} \\\\
\\hline
\\end{{tabularx}}
\\nointerlineskip
"""
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|S|V|V|V|}
\hline
\rowcolor{darkblue}
\textcolor{white}{\textbf{\scriptsize Guided Bend Test}} &
\textcolor{white}{\textbf{\scriptsize Type \& Figure}} &
\textcolor{white}{\textbf{\scriptsize Result}} &
\textcolor{white}{\textbf{\scriptsize Remarks}} \\
\hline
"""
    bends = d.get("bend_tests", [])
    for i in range(max(4, len(bends))):
        bg = r"\rowcolor{lightgray}" if i % 2 == 0 else ""
        if i < len(bends):
            b = bends[i]
            src += f"{bg} {_esc(b.get('specimen',''))} & {_esc(b.get('type',''))} & {_esc(b.get('result',''))} & {_esc(b.get('remarks',''))} \\\\\n\\hline\n"
        else:
            src += f"{bg} Specimen {i+1} & & & \\\\\n\\hline\n"

    src += r"""
\end{tabularx}
\nointerlineskip
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""RT/UT & {g('rt_ut')} & Fillet Weld Break & {g('fillet_break')} \\\\
\\hline
Macro Exam & {g('macro')} & Other & {g('other_tests')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("RANGES QUALIFIED")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|S|V|V|V|V|V|}
\hline
\rowcolor{darkblue}
\textcolor{white}{\textbf{\scriptsize }} &
\textcolor{white}{\textbf{\scriptsize Process}} &
\textcolor{white}{\textbf{\scriptsize F-No.}} &
\textcolor{white}{\textbf{\scriptsize Positions}} &
\textcolor{white}{\textbf{\scriptsize Thickness}} &
\textcolor{white}{\textbf{\scriptsize Diameter}} \\
\hline
""" + f"""Process 1 & {g('q1_process')} & {g('q1_f_number')} & {g('q1_positions')} & {g('q1_thickness')} & {g('q1_diameter')} \\\\
\\hline
\\rowcolor{{lightgray}} Process 2 & {g('q2_process')} & {g('q2_f_number')} & {g('q2_positions')} & {g('q2_thickness')} & {g('q2_diameter')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("CERTIFICATION")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Tested By & {g('tested_by')} & Test No. & {g('test_no')} \\\\
\\hline
Employer & {g('employer')} & Date & {g('test_date')} \\\\
\\hline
\\end{{tabularx}}
"""

    src += _sig_block()
    src += r"\end{document}"
    return src


# ═══════════════════════════════════════════════════════════════════════
#  FORM J-6 — REPORT OF RADIOGRAPHIC EXAMINATION OF WELDS
# ═══════════════════════════════════════════════════════════════════════

def latex_j6(d):
    g = lambda k: _esc(d.get(k, ""))
    src = _PREAMBLE + _footer("J-6", "Report of Radiographic Examination of Welds") + _DOC_BEGIN
    src += _title_block("J-6", "Report of Radiographic Examination of Welds")

    src += _section("PROJECT INFORMATION")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Project & {g('project')} & Date & {g('date')} & Report No. & {g('report_no')} \\\\
\\hline
Contractor & {g('contractor')} & Contract No. & {g('contract_no')} & & \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("EXAMINATION DETAILS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""RT Procedure No. & {g('rt_procedure')} & Technique (SWSI/DWSI/DWDI) & {g('technique')} \\\\
\\hline
Source Type & {g('source_type')} & Source Size & {g('source_size')} \\\\
\\hline
Film Type & {g('film_type')} & Screen Type & {g('screen_type')} \\\\
\\hline
Source-to-Film Distance & {g('sfd')} & Acceptance Criteria & {g('acceptance')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("EXAMINATION RESULTS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|S|V|S|V|V|V|V|}
\hline
\rowcolor{darkblue}
\textcolor{white}{\textbf{\scriptsize Weld ID}} &
\textcolor{white}{\textbf{\scriptsize Joint Type}} &
\textcolor{white}{\textbf{\scriptsize Thick.}} &
\textcolor{white}{\textbf{\scriptsize Indication}} &
\textcolor{white}{\textbf{\scriptsize Location}} &
\textcolor{white}{\textbf{\scriptsize Disposition}} &
\textcolor{white}{\textbf{\scriptsize Remarks}} \\
\hline
"""
    welds = d.get("welds", [])
    for i in range(max(8, len(welds))):
        bg = r"\rowcolor{lightgray}" if i % 2 == 0 else ""
        if i < len(welds):
            w = welds[i]
            src += f"{bg} {_esc(w.get('weld_id',''))} & {_esc(w.get('joint_type',''))} & {_esc(w.get('thickness',''))} & {_esc(w.get('indication',''))} & {_esc(w.get('location',''))} & {_esc(w.get('disposition',''))} & {_esc(w.get('remarks',''))} \\\\\n\\hline\n"
        else:
            src += f"{bg} & & & & & & \\\\\n\\hline\n"

    src += r"""
\end{tabularx}
\vspace{3pt}
"""

    src += _section("CERTIFICATION")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Examined By & {g('examined_by')} & Certification Level & {g('cert_level')} \\\\
\\hline
Reviewed By & {g('reviewed_by')} & Date & {g('review_date')} \\\\
\\hline
\\end{{tabularx}}
"""

    src += _sig_block()
    src += r"\end{document}"
    return src


# ═══════════════════════════════════════════════════════════════════════
#  FORM J-7 — REPORT OF MAGNETIC PARTICLE EXAMINATION OF WELDS
# ═══════════════════════════════════════════════════════════════════════

def latex_j7(d):
    g = lambda k: _esc(d.get(k, ""))
    src = _PREAMBLE + _footer("J-7", "Report of Magnetic Particle Examination of Welds") + _DOC_BEGIN
    src += _title_block("J-7", "Report of Magnetic Particle Examination of Welds")

    src += _section("PROJECT INFORMATION")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|D|V|}
\hline
""" + f"""Project & {g('project')} & Date & {g('date')} & Report No. & {g('report_no')} \\\\
\\hline
Contractor & {g('contractor')} & Contract No. & {g('contract_no')} & & \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("EXAMINATION DETAILS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""MT Procedure No. & {g('mt_procedure')} & Technique (Yoke/Prod/Coil) & {g('technique')} \\\\
\\hline
Magnetizing Current & {g('mag_current')} & Type (AC/DC/HWDC) & {g('current_type')} \\\\
\\hline
Particle Type & {g('particle_type')} & Application (Dry/Wet) & {g('application')} \\\\
\\hline
Surface Condition & {g('surface_condition')} & Acceptance Criteria & {g('acceptance')} \\\\
\\hline
Light Intensity & {g('light_intensity')} & Demagnetization & {g('demag')} \\\\
\\hline
\\end{{tabularx}}
\\vspace{{3pt}}
"""

    src += _section("EXAMINATION RESULTS")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|S|V|S|V|V|V|}
\hline
\rowcolor{darkblue}
\textcolor{white}{\textbf{\scriptsize Weld ID}} &
\textcolor{white}{\textbf{\scriptsize Joint Type}} &
\textcolor{white}{\textbf{\scriptsize Thick.}} &
\textcolor{white}{\textbf{\scriptsize Indication}} &
\textcolor{white}{\textbf{\scriptsize Disposition}} &
\textcolor{white}{\textbf{\scriptsize Remarks}} \\
\hline
"""
    welds = d.get("welds", [])
    for i in range(max(8, len(welds))):
        bg = r"\rowcolor{lightgray}" if i % 2 == 0 else ""
        if i < len(welds):
            w = welds[i]
            src += f"{bg} {_esc(w.get('weld_id',''))} & {_esc(w.get('joint_type',''))} & {_esc(w.get('thickness',''))} & {_esc(w.get('indication',''))} & {_esc(w.get('disposition',''))} & {_esc(w.get('remarks',''))} \\\\\n\\hline\n"
        else:
            src += f"{bg} & & & & & \\\\\n\\hline\n"

    src += r"""
\end{tabularx}
\vspace{3pt}
"""

    src += _section("CERTIFICATION")
    src += r"""
\noindent
\begin{tabularx}{\textwidth}{|D|V|D|V|}
\hline
""" + f"""Examined By & {g('examined_by')} & Certification Level & {g('cert_level')} \\\\
\\hline
Reviewed By & {g('reviewed_by')} & Date & {g('review_date')} \\\\
\\hline
\\end{{tabularx}}
"""

    src += _sig_block()
    src += r"\end{document}"
    return src


# ═══════════════════════════════════════════════════════════════════════
#  FORM REGISTRY
# ═══════════════════════════════════════════════════════════════════════

FORM_REGISTRY = {
    "J-1 — Procedure Qualification Record (PQR)": latex_j1,
    "J-2 — Welding Procedure Specification (WPS)": latex_j2,
    "J-3 — WPS Test Record (Electroslag / Electrogas)": latex_j3,
    "J-4 — Welder Qualification (Single-Process)": latex_j4,
    "J-5 — Welder Qualification (Multi-Process)": latex_j5,
    "J-6 — Radiographic Examination Report": latex_j6,
    "J-7 — Magnetic Particle Examination Report": latex_j7,
}
